---
- name: Check Netconf port 2222 open
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Checking Netconf connectivity
      wait_for:
        host: "{{inventory_hostname}}"
        port: 2222
        timeout: 5

    - name: Print the response
      debug:
        var: response 
