---
- hosts: centcmd
  tasks:
#    - name: Create database
#      mysql_db: db=ecomdb state=present
#
#    - name: Create database user
#      mysql_user: user=ecomuser password=ecompassword priv=*.*:ecomdb
#
    - name: Create a file
      file:
        path: "/home/Ansible/db-load-script.sql"
        state: touch

    - name: Add a content in a file
      lineinfile:
        path: "/home/Ansible/db-load-script.sql"
        line: 'USE ecomdb;\
          CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
          INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");'
    
    - name: Inject recently created SQL file
      command: "mysql < db-load-script.sql"

    - name: Update index file to point to localhost
      command: "sed -i 's/172.20.1.101/localhost/g' /var/www/html/index.php"
