-
  name: "Start Service in Order"
  hosts: all
  tasks:
    -
      name: "Start the services"
      service:
        name=mariadb
        state=started
    
        name=httpd
        state=started
