---
- name: Execute RPC
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: Get interface information
      juniper.device.rpc:
        rpcs: "get-interface-information"
      register: junos_result

    - name: Print response
      debug:
        var: junos_result
