---
- hosts: all
  roles:
    - "/root/.ansible/roles/juniper.junos"
  connection: local
  gather_facts: no
  
  vars_prompt:
    - name: "DEVICE_PASSWORD"
      prompt: "Device password"
      private: yes

  tasks:
    - name: New user
      juniper_junos_config:  
        config_mode: "private"
        user: root
        load: "set"
        src: "/home/ansible-content/username.set"
        diff: true
        check: true
        commit: true
      register: response
    - name: Print the changes
      debug:
        var: response
